### PR TITLE
chore: test using Python 2.7, 3.7, 3.10, and pypy-3.8

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by XadillaX** [comment]
I've mocked the data in test file. So I think we should add a `real world` test before this PR is landing.

**Comment by cclauss** [comment]
I am a bit confused.
This test is a `real world` test as these are actual versions of Python to test against rather than text in a file.

If you approve the workflow then we can see the results of the test run before considering merging it or not.

We might also want to [test on multiple OSes](https://github.com/nodejs/node-gyp/blob/master/.github/workflows/tests.yml#L10-L13).

**Comment by XadillaX** [comment]
> I am a bit confused. This test is a `real world` test as these are actual versions of Python to test against rather than text in a file.
> 
> If you approve the workflow then we can see the results of the test run before considering merging it or not.
> 
> We might also want to [test on multiple OSes](https://github.com/nodejs/node-gyp/blob/master/.github/workflows/tests.yml?rgh-link-date=2022-04-13T10%3A24%3A03Z#L10-L13).

That means I should add one more test case to test the real environment, but not only the mocked data. I'll do it later.

**Comment by cclauss** [comment]
So with the current code, if you run detect-python-interpreter, it does not actually detect the Python interpreter?

**Comment by XadillaX** [comment]
https://github.com/XadillaX/detect-python-interpreter/blob/master/test/index.test.js#L16

This package is, but the test cases is not. The test cases mocked the return value of `child_process` to test the logic of each situation.

**Comment by XadillaX** [comment]
@cclauss It seems all test environments have Python3 installed.

**Pull request merged**
